CREATE TABLE "suppliers" (
  "supplier_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_name" VARCHAR(65) NOT NULL,
  "contact_info" VARCHAR(255) NOT NULL
);

CREATE TABLE "customers" (
  "customer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" VARCHAR(65) NOT NULL,
  "last_name" VARCHAR(65) NOT NULL,
  "phone_number" VARCHAR(30) NOT NULL
);

CREATE TABLE "parts" (
  "part_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "part_name" VARCHAR(128) NOT NULL,
  "description" VARCHAR(255) NOT NULL,
  "units_in_stock" INTEGER NOT NULL,
  "retail_price" DECIMAL(10,2) NOT NULL
);

CREATE TABLE "delivery_requests" (
  "request_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "supplier_id" INTEGER NOT NULL,
  "request_date" DATE NOT NULL,
  "part_id" INTEGER NOT NULL,
  "quantity" INTEGER NOT NULL,
  FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("supplier_id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("part_id") REFERENCES "parts"("part_id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "deliveries" (
  "delivery_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "delivery_date" DATE NOT NULL
);

CREATE TABLE "delivery_details" (
  "delivery_id" INTEGER NOT NULL,
  "request_id" INTEGER NOT NULL,
  "quantity" INTEGER NOT NULL,
  "selling_price" DECIMAL(10,2) NOT NULL,
  PRIMARY KEY ("delivery_id", "request_id"),
  FOREIGN KEY ("delivery_id") REFERENCES "deliveries"("delivery_id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("request_id") REFERENCES "delivery_requests"("request_id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "sales" (
  "sale_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" INTEGER NOT NULL,
  "sale_date" DATE NOT NULL,
  FOREIGN KEY ("customer_id") REFERENCES "customers"("customer_id")
);

CREATE TABLE "sale_details" (
  "sale_id" INTEGER NOT NULL,
  "part_id" INTEGER NOT NULL,
  "retail_price" DECIMAL(10,2) NOT NULL,
  "quantity" INTEGER NOT NULL,
  PRIMARY KEY ("sale_id", "part_id"),
  FOREIGN KEY ("sale_id") REFERENCES "sales"("sale_id") ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY ("part_id") REFERENCES "parts"("part_id") ON DELETE CASCADE ON UPDATE CASCADE
);
