services:
  neo4j:
    container_name: neo4j
    image: neo4j:enterprise
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/data/
    env_file:
      - .env

volumes:
  neo4j_data:

    