services:
  mysql:
    container_name: l3-db1
    image: mysql:latest
    restart: on-failure
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql

  postrgres:
    container_name: l3-db2
    image: postgres:latest
    restart: on-failure
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbeaver:
    container_name: l3-dbadmin
    image: dbeaver/cloudbeaver
    restart: on-failure
    ports:
      - 8978:8978

volumes:
  mysql_data:
  postgres_data:
